### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by ocdtrekkie** [blumk/ChipsChallenge-UWP#4]
I hate to be the one to ask this, but I feel it's worth asking. Is there a license attached to this source? Is it open source? Is any necessary trademark and/or licensing questions settled? The Java version appears to describe itself as a "clone", and similarly doesn't mention any matter of legality.

**Comment by blumk** [comment]
There is no licence attached to the game engine, maybe the original author of the Java implementation could provide one. The game assets (images, sounds and level set) might be copyrighted by Microsoft.

**Comment by ocdtrekkie** [comment]
Both are particularly problematic, then. Game assets could definitely open you up to a DMCA takedown notice if permission to use the assets cannot be found. And while the Java implementation author may have posted his source code on GitHub, without a license declared, it's technically proprietary code as well.

I've opened up an issue to ask the Java author about both topics.

Note that things like the former web-based StarCraft clone that was up on GitHub got DMCA'd for asset use, and noting that Chip's Challenge 2 is a recent thing, and even the original Chip's Challenge dude had a hard time getting permission to use the trademark for the game he originally made, I strongly suspect if this project gets enough media attention that it could have a DMCA filed against it.

**Comment by RAMPKORV** [comment]
I took down my repo now. It's my simple way of handling this. For me it was a great case study to see if one could make an OO model of this game.

**Comment by ocdtrekkie** [comment]
@RAMPKORV It's a great piece of code. But yeah, I'm just concerned this will sadly run afoul of things.

In the case of @blumk, I'm super excited to see this as a UWP app, but I imagine it will eventually at some point attract attention from the dev and get pulled. I almost wonder if the original dev would be interested in officially offering this as a UWP version or not.

**Comment by blumk** [comment]
Thank you @RAMPKORV for providing the game engine.

@ocdtrekkie: There are two companies form the US/UK that have the name "Chip's Challenge" trademarked. I guess Microsoft must have obtained a license from them. In that case I'll remove this repo from GitHub until I figure out how to handle the legal stuff.
