### ISSUE TITLE
Incorrect trap behavior in LADDER (36) / THREE DOORS (46)

### ISSUE THREAD

**Issue by chausner** [blumk/ChipsChallenge-UWP#6]
In level LADDER (36), pressing the brown button should move the tank (as seen [here](http://chipschallenge.wikia.com/wiki/Ladder)) but it does nothing, making the level impossible to complete.

**Comment by blumk** [comment]
A similar bug occurs in level THREE DOORS (46): Pressing the brown button should release the pink ball from the trap.
![image](https://cloud.githubusercontent.com/assets/2436496/17269173/2f4e7f00-5642-11e6-8615-39fb1c112c01.png)
